version: '3.1'

services:

  rabbit:
    image: rabbitmq:3.7.8
    hostname: rabbit
    container_name: rabbit
    ports:
      - 5672:5672

  redis:
    image: redis:4.0.11-alpine
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379

  maria:
    image: mariadb:10.3.10
    restart: always
    hostname: maria
    container_name: maria
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf